import type { Metadata } from "next";
import { Roboto } from 'next/font/google';
import { LanguageProvider } from "../context/LanguageContext"; 
import Image from "next/image";
import WorldMap from "../../public/images/WorldMap-.png";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"], 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased relative w-full h-screen`}
      >
        <div className="absolute top-0 left-0 w-full h-full z-[-1]">
          <Image 
            src={WorldMap} 
            alt="World Map" 
            layout="fill" 
            objectFit="cover" 
            priority={true} 
          />
        </div>
        <LanguageProvider>
          {children}
        </LanguageProvider>
      </body>
    </html>
  );
}
